// scripts/ontology-report.cjs — `npm run report:ontology`
//
// How far the herb records are from a formulation ontology (external
// audit 2026-09-29, #28): for each section the audit proposed, which
// fields exist, on how many of the herbs, whether the formula engine
// reads them, and what is still missing. Writes docs/ONTOLOGY.md.
// Rerun it after herb data work to see the gaps close.

const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const HERBS = require(path.join(ROOT, 'src/server/herb-data/herbs.generated.cjs'));
const ENGINE_DIR = path.join(ROOT, 'src/server/formula-engine');
const engineSrc = fs.readdirSync(ENGINE_DIR).filter(f => f.endsWith('.js'))
  .map(f => fs.readFileSync(path.join(ENGINE_DIR, f), 'utf8')).join('\n');

// A field counts as recorded when it holds something (not empty).
const present = (h, f) => { const v = h[f]; return !(v === undefined || v === null || v === '' || (Array.isArray(v) && !v.length)); };
const count = f => HERBS.filter(h => present(h, f)).length;
// "Read by the engine": the field name used as a property in the engine.
const read = f => new RegExp('\\.' + f + '\\b|[\'"]' + f + '[\'"]').test(engineSrc);

// [field, note]. A null field is a MISSING item: named, not yet recorded.
const SECTIONS = [
  ['Identity', [
    ['botanical', 'binomial, with the part often in brackets'],
    ['family', 'drives fungi and Amanita rules'],
    ['aliases', 'other names; German names for ~50 herbs live in note-safety.js'],
    [null, 'part used (root / leaf / fruit…) as its own field — today inside `botanical` text'],
  ]],
  ['Goal profile', [
    ['goals', 'ordered; the first is the main use and scores most'],
    [null, 'goal scores (strength per goal), not only order'],
  ]],
  ['Constitution', [
    ['energetics', 'prose'],
    ['tcm_element', ''],
    ['tcm_meridians', ''],
    ['nervous_system_fit', 'pro / nervous-system answers'],
    [null, 'pattern affinities and exclusions (hot / cold / mixed / depleted, and the 16 sub-answers) as data — today derived from prose'],
  ]],
  ['Rhythm', [
    ['onset_time', ''],
    ['energy_pattern', ''],
    ['sleep_action', ''],
  ]],
  ['Pharmacology', [
    ['cns_action', 'unrecorded = neutral; every sedative / stimulant the engine counts is recorded'],
    ['serotonergic', 'absent = no'],
    ['laxative', 'recorded 2026-09-29 (was a word search)'],
    [null, 'load dimensions as numbers (sedative, stimulant, serotonergic, hepatic, anticoagulant load) instead of yes / no classes'],
  ]],
  ['Safety', [
    ['caution_level', ''],
    ['contraindications', 'prose'],
    ['herb_to_drug_interactions', 'prose'],
    ['safe_pregnancy', 'unknown = avoid'],
    ['formula_access', "'pro' = pro composer only"],
    [null, 'drug-interaction class as data (e.g. CYP3A4, anticoagulant, serotonergic, MAOI)'],
    [null, 'lactation, as its own field (today folded into the pregnancy answer)'],
    [null, 'age limits (today the under-18 gate reads CNS class and caution level)'],
  ]],
  ['Formulation', [
    ['trace_class', 'recorded 2026-09-29 (was a name list): aromatic / pungent / bitter / resin'],
    ['max_share_pct', 'Saffron 7% (Robin, 2026-09-29)'],
    ['digestion_fit', ''],
    ['herb_to_herb_caution', 'prose; the ruled-out pairs live in pair-rules.js (8 BLOCK, 15 CONDITIONAL)'],
    ['herb_to_herb_synergy', 'prose'],
    [null, 'minimum share'],
    [null, 'interaction severity per pair on the herb record (today pair-rules.js)'],
  ]],
  ['Role potential', [
    [null, 'primary / bridge / foundation / regulator / trace — the roles work; needs Robin\'s data'],
  ]],
  ['Evidence', [
    ['evidence_grade', 'scores 0 to +2'],
    ['references', ''],
    ['research_notes', ''],
    ['cns_evidence', 'the source behind cns_action'],
    [null, 'source, date and confidence behind each value'],
  ]],
];

const n = HERBS.length;
const pct = c => Math.round(c / n * 100);
let md = '# The herb records as a formulation ontology\n\n' +
  'Generated by `npm run report:ontology` (`scripts/ontology-report.cjs`) from the live catalogue — **' + n + ' herbs**. ' +
  'Sections from the external audit of 2026-09-29, #28. "Engine" = the formula engine reads the field. ' +
  'Missing items are the data still to gather; the roles work needs Robin\'s input.\n\n';
let have = 0, missing = 0;
for (const [title, fields] of SECTIONS) {
  md += '## ' + title + '\n\n| Field | Herbs | Engine | Note |\n|---|---|---|---|\n';
  for (const [f, note] of fields) {
    if (!f) { missing++; md += '| — *missing* | 0 | — | ' + note + ' |\n'; continue; }
    have++;
    const c = count(f);
    md += '| `' + f + '` | ' + c + ' / ' + n + ' (' + pct(c) + '%) | ' + (read(f) ? 'yes' : 'no') + ' | ' + note + ' |\n';
  }
  md += '\n';
}
md += '---\n\n' + have + ' fields recorded, ' + missing + ' still missing.\n';
fs.writeFileSync(path.join(ROOT, 'docs/ONTOLOGY.md'), md);
console.log('✓ docs/ONTOLOGY.md — ' + have + ' fields recorded, ' + missing + ' missing, ' + n + ' herbs');
