name: 🚀 Deploy
on:
  push:
    branches:
      - beta
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Install and Build
        # ADD THE LINE BELOW (Make sure it matches your folder name exactly)
        working-directory: ./fungai-art 
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: 🚀 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./beta/